version = 0.1
[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vdn6yiv62t2m"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "parkingLot-app"
s3_bucket = "s3bucket-for-parking-lot-deploy"
s3_prefix = "parkingLot-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
