version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "parkingLot-app"
s3_bucket = "aws-sam-deploy-bucket"
s3_prefix = "parkingLot-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
