AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  untitled

  Sample SAM Template for untitled

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: 'Test'

  exitlambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'ExitLambdaTest'
      CodeUri: parking_lot/
      Handler: Exitapp.exit_lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Policies:
       - AmazonS3FullAccess
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /exit
            Method: POST
            ApiId: !Ref HttpApi
  entrylambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'EntryLambdaTest'
      CodeUri: parking_lot/
      Handler: Entryapp.entry_lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Policies:
       - AmazonS3FullAccess
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /entry
            Method: POST
            ApiId: !Ref HttpApi

  parkinglots3:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: parkinglots3

